---
plugins:
  fixme:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc
  nodesecurity:
    enabled: true
  requiresafe:
    enabled: true
exclude_patterns:
- node_modules/**/*
- test/**/*
- error/**/*
version: "2"
