env:
  es6: true
  node: true
parser: 'babel-eslint'
extends: 'goodparts'
overrides:
  - files:
      - index.js
    rules:
      space-before-function-paren: 'warn'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
