branches:
  - main
  - name: beta
    channel: beta
    prerelease: beta
ci: false
dryRun: false
debug: false
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
  - - '@semantic-release/npm'
  - - '@semantic-release/github'
