branch: master
ci: false
plugins:
  - - '@semantic-release/commit-analyzer'
    - releaseRules:
        - type: build
          release: patch
        - type: ci
          release: patch
        - type: chore
          release: patch
        - type: docs
          release: patch
        - type: refactor
          release: patch
        - type: style
          release: patch
        - type: test
          release: patch
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG_v2.md'
      changelogTitle: 'CHANGELOG'
  - - '@semantic-release/npm'
    - npmPublish: true
  - - '@semantic-release/git'
    - message: 'chore(release): ${nextRelease.version} [skip ci]'
  - '@semantic-release/github'
